### ISSUE TITLE
Configurable DocumentRoot directory name?

### ISSUE THREAD

**Issue by edlazaro** [estebanspina/lamp#2]
The VM image has the Apache DocumentRoot set to /var/www/public.
Vagrant's config file syncs the project's "./" to the VM's "/var/www", thus requiring the web directory to be named "public" to match the VM's config .
For cases like Drupal 9, where the web directory (DocumentRoot) is called "web" and not "public", and there is no easy way to rename it, it would be very useful to have a way to configure the name of this web directory , so you don't have to change the apache configuration on the VM.
![image](https://user-images.githubusercontent.com/22231165/170635705-ece49848-7188-4ea2-9488-fa4876713534.png)

**Comment by estebanspina** [comment]
As I said, this is a very flexible virtual machine that allows you to create a simple Ubuntu Server 20.04 LTS (Focal Fossa) for LAMP stack developers which also includes many related modern development tools.

Not an Issue, this is NOT a Drupal VM.
